### ISSUE TITLE
Hire a videographer

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/jamstack.nyc#2]
Requirements:

About

We are a technology-oriented event series focused on informing and inspiring professional web designers and developers about new technologies, collectively referred to as "JAMstack."

Details

- We hold approximately nine events per year. 
- We don't have a set schedule for the events as we try to accommodate our speakers' schedules.
- We tend to have our events at a handful of venues, but we don't have a permanent home. 
- Attendance ranges from 20 to 60 people (it varies quite a bit because we don't charge attendance)
- Our speakers are a mix of professional speakers (typically people at a "developers relations" role at a tech company) and non-professional practitioners. 
- The talks are typically technical in nature, and include slides. 

Timing

- We have two speakers per event, with each session lasting 30-45 minutes. We also have an introduction, but do not expect to record them. 
- Events begin at 6:30 p.m., with speaker sessions starting closer to 7pm, with a very short break between sessions.

Videos

- Work includes setup/filming/takedown + editing and delivery to our Youtube channel.
- We like the videos to include both the  speaker and their slides. The videos have a long shelf-life after the event. 
- We have recently updated our graphics and can work with the editor to supply a standard set of grahpics. 
- Videos are currently hosted on Youtube. 
- Videos should include a link back to our website.
- We may consider livestream for select events.

Budget

- Our last person charged $200 for a typical event, with $100 extra for Livestream. 
- We are willing to revise our budget, if necessary, though it could not go too much higher.
- We have food and beverages at our events and you are welcome to eat/drink. 

Scheduling

- We would like to schedule each event one or more months in advance. 
- We are currently working to plan farther ahead and would want to try setting a tentative schedule as far in advance as possible.
- We value reliability, and would like to have a backup plan.

We are an informal group, but we have a code of conduct that we expect everyone on our team to adhere to.

**Comment by budparr** [comment]
@rayrshah @futuregerald for your comment before I send it to some folks

**Comment by futuregerald** [comment]
This is well thought out and describes the event and our needs.

**Comment by rayrshah** [comment]
I agree. This is very thorough. Thanks for sharing
