### ISSUE TITLE
July 30th,31st or August 1st Meetup

### ISSUE THREAD

**Issue by futuregerald** [theNewDynamic/jamstack.nyc#9]
## Event Description
- [x] List Speakers, with Twitter handle
- [ ] Outline topics
Speakers
- Nader Dabit
Twitter: @dabit3
Bio: Details upcoming, but Nader works as a dev advocate for AWS mobile, and specifically works on the AppSync side. He previously did React Native training, and does React on the frontend as well. Nader is in Mississippi. 

## Venue
- [ ] Venue name
- [ ] Special requirements
- [ ] List venue contacts

## Food & Beverage 
- [ ] Catering option

## Technical
- [ ] Videography

**Comment by dabit3** [comment]
I just submitted a request for event space at the AWS Soho Loft. I'll update this thread as soon as I hear something back!

**Comment by dabit3** [comment]
@futuregerald what is the estimated number of attendees to an event like this?

**Comment by dabit3** [comment]
Also @futuregerald , is there going to be any other speakers? If so, do you mind giving me their name & the talk info (if available)? Thanks.

**Comment by futuregerald** [comment]
Hi @dabit3 , we are working on the second speaker now but we haven't confirmed anyone else yet.  We would like to get 50+ people. We are planning this pretty far in advance so hopefully we can get a bigger crowd.

**Comment by dabit3** [comment]
Ok cool. I think I need to have the speaker info confirmed to finalize the event space (the legal team needs it). When do you think you may have this info? I know it's pretty far in advance, sorry if this is an inconvenience.

**Comment by futuregerald** [comment]
@dabit3 the second speaker is Divya Sasidharan, @shortdiv on twitter. You may know her from "Views on Vue " on DevChat.tv

**Comment by dabit3** [comment]
Thanks @futuregerald !

**Comment by dabit3** [comment]
Ok, looks like this event has officially been approved & booked for August 1!

@futuregerald What do you think you would need from me for the next steps?

**Comment by dabit3** [comment]
ping @futuregerald

**Comment by futuregerald** [comment]
That's great, sorry was caught up in prepping for JAMstack_conf_nyc that was last week (https://jamstackconf.com/nyc/)

We would love to have your bio, and a description of the talk. If you'd like to chat about the contents of your talk then I'm available and we can schedule a quick call.

**Comment by dabit3** [comment]
@futuregerald Awesome! No worries, & here's the requested info:

Nader Dabit
Bio: Web & mobile developer, author, Developer Advocate at Amazon Web Services.

Re: Talk info, let's chat about this! What are some available times? My email is dabit@amazon.com

**Comment by budparr** [comment]
Hey, @dabit3 We're going to start promoting the event now. Here's the event on Meetup: https://www.meetup.com/JAMstack-nyc/events/261268213/

cc/ @futuregerald

**Comment by budparr** [comment]
And I submitted a PR to the AWS event site to update the link: https://github.com/aws-amplify/community/pull/96
